### ISSUE TITLE
Want to convert it into and application

### ISSUE THREAD

**Issue by Dawoodsarfraz** [Tarferi/youtubedownloader#1]

**Comment by Tarferi** [comment]
Provide further details. There is a refactor planned.

**Comment by Dawoodsarfraz** [comment]
Actually i was working on a project and want to make an application to download Videos from youtube. I saw your repo and interested to embed you code into GUI application. Can to share me some resources for c language. To understand your code?

**Comment by Tarferi** [comment]
Most of the code for this project was taken from another private project that continuously evolved into an amalgamate of a solution. You can either embed released command line executable or wait for the refactor that will externalize further parts of the other project, including public API. Including sources of the current state of the code is not recommended as it is written very poorly.

**Comment by Dawoodsarfraz** [comment]
I need some resources (Univeristy Course, YouTube, Blog, Videos) to learn c/c++ language like used by in this repos. I now c/c++ but unable to understand this as you have used many files ([Cache.cpp], [Cache.h], [Youtube.cpp], [YoutubeDownloader.cpp], [common.cpp], [common.h]
, [json.h], [md5.h], [minimp4.h], [miniz.cpp], [miniz.h], [output.cpp], [output.h]). 

Can you please help me? Kindly share your email.

**Comment by Tarferi** [comment]
I, sadly, do not offer services of a personal tutor, C/C++ or otherwise.

**Comment by Dawoodsarfraz** [comment]
I need resouces kindly share. I shall be very thankful to you.
